[project]
name = "battery-data"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = ["pandas", "pyarrow", "duckdb", "pydantic>=2", "typing-extensions"]
[project.optional-dependencies]
dev = ["pytest", "ruff", "mypy", "pytest-cov"]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
