[project]
name = "battery-models"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = ["numpy", "scipy", "typing-extensions", "torch"]
[project.optional-dependencies]
dev = ["pytest", "ruff", "mypy", "pytest-cov"]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
